# storageClassName: local-path (k3d default — no necesita provisioner externo)
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pythonapps-trigger-template
  namespace: tekton-pipelines
spec:
  params:
  - name: repo-url
  - name: app-name
  - name: image-tag
  - name: environment
    default: dev
  - name: strategy
    default: rollingupdate
  - name: base-url
    default: ""
  - name: preview-url
    default: ""
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.app-name)-run-
      namespace: tekton-pipelines
    spec:
      pipelineRef:
        name: pythonapps-pipeline
      podTemplate:
        tolerations:
        - key: workload
          value: cicd
          operator: Equal
          effect: NoSchedule
        nodeSelector:
          role: cicd
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: app-name
        value: $(tt.params.app-name)
      - name: image-tag
        value: $(tt.params.image-tag)
      - name: image-full
        value: "docker.io/{{ .Values.tekton.dockerhubUser }}/$(tt.params.app-name):$(tt.params.image-tag)"
      - name: environment
        value: $(tt.params.environment)
      - name: strategy
        value: $(tt.params.strategy)
      - name: gitops-repo-url
        value: "{{ .Values.tekton.gitopsRepoUrl }}"
      - name: base-url
        value: $(tt.params.base-url)
      - name: preview-url
        value: $(tt.params.preview-url)
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: local-path
            resources:
              requests:
                storage: 2Gi
      - name: gitops
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: local-path
            resources:
              requests:
                storage: 1Gi
