{{- if .Values.tekton.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pythonapps-trigger-template
  namespace: tekton-pipelines
spec:
  params:
  - name: repo-url
  - name: app-name
  - name: image-tag
  - name: revision
    default: main
  - name: environments
    default: dev
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.app-name)-run-
      namespace: tekton-pipelines
    spec:
      pipelineRef:
        name: pythonapps-pipeline
      taskRunTemplate:
        serviceAccountName: tekton-pipeline-runner
      podTemplate:
        tolerations:
        - key: workload
          value: cicd
          operator: Equal
          effect: NoSchedule
        nodeSelector:
          role: cicd
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: app-name
        value: $(tt.params.app-name)
      - name: image-tag
        value: $(tt.params.image-tag)
      - name: revision
        value: $(tt.params.revision)
      - name: image-full
        value: "docker.io/{{ .Values.tekton.dockerhubUser }}/$(tt.params.app-name):$(tt.params.image-tag)"
      - name: environments
        value: $(tt.params.environments)
      - name: gitops-repo-url
        value: "{{ .Values.tekton.gitopsRepoUrl }}"
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: local-path
            resources:
              requests:
                storage: 2Gi
      - name: gitops
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: local-path
            resources:
              requests:
                storage: 1Gi
{{- end }}
