{{- if .Values.tekton.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-tag-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: app-name
    value: $(body.repository.name)
  - name: image-tag
    value: $(extensions.image_tag)
  - name: environments
    value: $(extensions.environments)
  - name: revision
    value: $(extensions.git_revision)
{{- end }}
