apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: belo-challenge
servers: 1
agents: 3
ports:
  - port: 8888:80
    nodeFilters: [loadbalancer]
volumes:
  - volume: belo-statefull-data:/mnt/statefull
    nodeFilters: [agent:0]
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters: [server:0]
      - arg: --disable=servicelb
        nodeFilters: [server:0]
